#!/bin/bash

#Kindle-id, a program to pull ASIN id's from an amazon series page.
#Copyright (C) 2024  Freaker2112
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

html=$1

echo "!!! IMPORTANT !!!"
echo "This script DOES NOT have API access to the amazon storefront!"
echo "You MUST save a local copy of the html of the series page for your series"
echo ""
echo "-----------"
echo ""
echo "Please provide all paths relative to current directory"
echo ""
echo "Working Directory: $PWD"
echo ""

if ! [ -f "$PWD/$html" ]; then
 echo "What is the location of your html file?"
 read html
fi

if ! [ -f "$PWD/$html" ]; then
  echo "File does not exist."
  exit
fi

if [ -f "$PWD/$html" ]; then
  echo "File Found..."
fi

echo "What is a string that every title contains? (eg. 'Vol.')"
read findstr
echo "looking for ASINs in $html with $findstr..."

cat "$html" |grep "$findstr"|grep -o -P "(?<=\/product\/)B[0-9][A-Z 0-9]{8}"

echo ""
echo "this is a WIP!"
