#!/bin/bash
html=$1

echo "!!! IMPORTANT !!!"
echo "This script DOES NOT have API access to the amazon storefront!"
echo "You MUST save a local copy of the html of the series page for your series"
echo ""
echo "-----------"
echo ""
echo "Please provide all paths relative to current directory"
echo ""
echo "Working Directory: $PWD"
echo ""

if ! [ -f "$PWD/$html" ]; then
 echo "What is the location of your html file?"
 read html
fi

if ! [ -f "$PWD/$html" ]; then
  echo "File does not exist."
  exit
fi

if [ -f "$PWD/$html" ]; then
  echo "File Found..."
fi

echo "What is a string that every title contains? (eg. 'Vol.')"
read findstr
echo "looking for ASINs in $html with $findstr..."

cat "$html" |grep "$findstr"|grep -o -P "(?<=\/product\/)B[0-9][A-Z 0-9]{8}"

echo ""
echo "this is a WIP!"
